node-linker: hoisted
link-workspace-packages: true
publicHoistPattern:
  - "*prettier*"
packages:
  - packages/*
  - playground

onlyBuiltDependencies:
  - core-js
  - esbuild
  - simple-git-hooks
  - unrs-resolver
